### ISSUE TITLE
now export ast not working on python 3.8

### ISSUE THREAD

**Issue by Felipe-CdS** [gems-uff/noworkflow#192]
`now export ast` without any flags `--json` or `--dot` leads to the method:

https://github.com/gems-uff/noworkflow/blob/d4ffe7aa424ad71dfdc03d1f27989d4f399e78e2/src/noworkflow/now/models/ast/trial_ast.py#L663-L664

`indent` was added to ast module on Python 3.9, so any user that follows the README.md installation instructions and tries to run noworkflow using python 3.8 will get an error. 

```
  File "/app/.venv/lib/python3.8/site-packages/noworkflow/now/models/ast/trial_ast.py", line 664, in construct_ast
    print(ast.dump(ast.parse(self()), indent=2))
TypeError: dump() got an unexpected keyword argument 'indent'
``` 

Do we want to bump the whole project version? Or keep it as it is and remove the method argument?
Other issues could benefit from a python version bump, e.g. https://github.com/gems-uff/noworkflow/issues/156

**Comment by TiberiusNemesis** [comment]
yep, this is a py3.8 compat bug. The project still says `requires-python = ">=3.8"` and the README still uses Python 3.8, so I kept 3.8 working instead of bumping the floor.

opened #193. the fix only passes `indent=2` on Python 3.9+. Python 3.8 gets the plain `ast.dump` output.

I tested it out with small isolated test and 3.8/3.9 are both working
